// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // মাইগ্রেশনের জন্য আমরা সরাসরি Direct URL ব্যবহার করব (PgBouncer bypassed)
    url: process.env["DIRECT_URL"],
  },
});